In [1]:
import polars as pl
from datasets import load_dataset, load_from_disk
from replay.metrics import Recall, Precision, HitRate
import pandas as pd

In [2]:
item2item_recs = pl.read_parquet("../item2item/data/best_item2item_recs.parquet")
user2vec_recs = pl.read_parquet("../user2vec/data/user2vec_recs_v2.parquet")
ials_recs = pl.read_parquet("../ials/data/ials_recs_v2.parquet")
neural_item2item_recs = pl.read_parquet("../neural_item2item/data/item2item_recs.parquet")
co_liked_recs = pl.read_parquet("../item_co_occurance/co_liked_recs_v2.parquet")

In [31]:
all_recs = (
    item2item_recs
    .join(
        user2vec_recs,
        on="user_id",
        how="inner"
    )
    .join(
        ials_recs,
        on="user_id",
        how="inner"
    )
    .join(
        neural_item2item_recs,
        on="user_id",
        how="inner"
    )
    .join(
        co_liked_recs,
        on="user_id",
        how="inner"
    )
)

In [19]:
all_recs.head(5)

shape: (5, 7)
┌──────────┬──────────────┬────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ user_id  ┆ last_clicks  ┆ item2item_ ┆ user2vec_rec ┆ ials_recs    ┆ neural_item2 ┆ co_liked_rec │
│ ---      ┆ ---          ┆ recs       ┆ s            ┆ ---          ┆ item_recs    ┆ s            │
│ i64      ┆ list[i64]    ┆ ---        ┆ ---          ┆ list[i64]    ┆ ---          ┆ ---          │
│          ┆              ┆ list[i64]  ┆ list[i64]    ┆              ┆ list[i64]    ┆ list[i64]    │
╞══════════╪══════════════╪════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ 14093892 ┆ [234652449,  ┆ [234652449 ┆ [117277008,  ┆ [167392398,  ┆ [52545540,   ┆ []           │
│          ┆ 204938610,   ┆ ,          ┆ 171686736, … ┆ 3432615, …   ┆ 21126704, …  ┆              │
│          ┆ 157844389…   ┆ 24725041,  ┆ 84356]       ┆ 53981912]    ┆ 224856720…   ┆              │
│          ┆              ┆ …          ┆              ┆              ┆              ┆              │
│          ┆              ┆ 25890823…  ┆              ┆              ┆              ┆              │
│ 43635824 ┆ [190925215,  ┆ [190925215 ┆ [134898986,  ┆ [34096337,   ┆ [239138284,  ┆ [167828822,  │
│          ┆ 62715930, …  ┆ ,          ┆ 143420921, … ┆ 82817719, …  ┆ 186924312, … ┆ 187498156, … │
│          ┆ 18646571…    ┆ 86058273,  ┆ 1668687…     ┆ 186724001…   ┆ 2239848…     ┆ 2565275…     │
│          ┆              ┆ …          ┆              ┆              ┆              ┆              │
│          ┆              ┆ 70295544…  ┆              ┆              ┆              ┆              │
│ 51312652 ┆ [78187513,   ┆ [219222831 ┆ [241574441,  ┆ [41015722,   ┆ [95956891,   ┆ [134568799,  │
│          ┆ 154325377, … ┆ ,          ┆ 1078426, …   ┆ 207254134, … ┆ 12397437, …  ┆ 211966411, … │
│          ┆ 22402361…    ┆ 78187513,  ┆ 174717899…   ┆ 25607076…    ┆ 201331724…   ┆ 1202802…     │
│          ┆              ┆ …          ┆              ┆              ┆              ┆              │
│          ┆              ┆ 12500294…  ┆              ┆              ┆              ┆              │
│ 26806012 ┆ [119852251,  ┆ [119852251 ┆ [152335420,  ┆ [142049504,  ┆ [51392190,   ┆ []           │
│          ┆ 10760442,    ┆ ,          ┆ 213949254, … ┆ 164604147, … ┆ 57042515, …  ┆              │
│          ┆ 152335420]   ┆ 58458760,  ┆ 1058304…     ┆ 1893261…     ┆ 97127944]    ┆              │
│          ┆              ┆ …          ┆              ┆              ┆              ┆              │
│          ┆              ┆ 18228697…  ┆              ┆              ┆              ┆              │
│ 28921764 ┆ [231708087,  ┆ [231708087 ┆ [169859264,  ┆ [84510695,   ┆ [163333485,  ┆ []           │
│          ┆ 172347039, … ┆ ,          ┆ 195154229, … ┆ 119653164, … ┆ 72951261, …  ┆              │
│          ┆ 1134212…     ┆ 120656215, ┆ 7649617…     ┆ 15724890…    ┆ 19602334…    ┆              │
│          ┆              ┆ … 1181639… ┆              ┆              ┆              ┆              │
└──────────┴──────────────┴────────────┴──────────────┴──────────────┴──────────────┴──────────────┘

In [32]:
def join_recs(row):
    joined_recs = set()
    for key in row:
        if "recs" in key:
            joined_recs = joined_recs | set(row[key])
    return list(joined_recs)

joined_recs = (
    all_recs
    .with_columns(
        pl.struct(["user2vec_recs", "item2item_recs", "ials_recs", "co_liked_recs", "neural_item2item_recs"]).apply(join_recs).alias("recs")
    )
    .select("user_id", "recs")
)

In [24]:
joined_recs.write_parquet("all_candidatates_recs.parquet")

In [42]:
DATA_PATH = "/home/jupyter/filestore/storage/datasets/user_clicks_20230501"

dataset = load_from_disk(DATA_PATH)

In [39]:
polars_ds = dataset.to_polars()

In [7]:
TRAIN_END_DT = pd.to_datetime("2023-05-14")

train_items = (
    polars_ds
    .with_columns(pl.col("stime").cast(pl.Date).alias("date"))
    .filter(pl.col("date") <= TRAIN_END_DT)
    .select("item_id")
    .unique()["item_id"]
    .to_list()
)

In [7]:
TRAIN_END_DT = pd.to_datetime("2023-05-14")
TEST_END_DT = pd.to_datetime("2023-05-21")

test_interactions = (
    polars_ds
    .with_columns(pl.col("stime").cast(pl.Date).alias("date"))
    .filter(pl.col("date") > TRAIN_END_DT)
    .filter(pl.col("date") <=  TEST_END_DT)
    .groupby("user_id")
    .agg(pl.col("item_id").alias("future_clicks"))
    .join(
        joined_recs,
        on="user_id",
        how="inner"
    )
    .with_columns(pl.col("recs").apply(len).alias("recs_count"))
)

In [8]:
recs_stats = (
    test_interactions
    .with_columns(pl.col("recs").apply(len).alias("recs_count"))
    .select(
        pl.min("recs_count").alias("min_recs_count"),
        pl.mean("recs_count").alias("mean_recs_count"),
        pl.max("recs_count").alias("max_recs_count"),
    )
)

recs_stats

shape: (1, 3)
┌────────────────┬─────────────────┬────────────────┐
│ min_recs_count ┆ mean_recs_count ┆ max_recs_count │
│ ---            ┆ ---             ┆ ---            │
│ i64            ┆ f64             ┆ i64            │
╞════════════════╪═════════════════╪════════════════╡
│ 756            ┆ 1454.908481     ┆ 3973           │
└────────────────┴─────────────────┴────────────────┘

In [15]:
TOP_K_VALUES = [10, 100, 3973]

def calc_recall(row):
    return Recall._get_metric_value_by_user(TOP_K_VALUES, row["future_clicks"], row["recs"])

def calc_precision(row):
    return Precision._get_metric_value_by_user(TOP_K_VALUES, row["future_clicks"], row["recs"])

def calc_hitrate(row):
    return HitRate._get_metric_value_by_user(TOP_K_VALUES, row["future_clicks"], row["recs"])

def intersection(row):
    return len(set(row["recs"]) & set(row["future_clicks"]))

metrics = (
    test_interactions
    .with_columns(
        pl.struct(["future_clicks", "recs"]).apply(calc_recall).alias("recall"),
        pl.struct(["future_clicks", "recs"]).apply(calc_precision).alias("precision"),
        pl.struct(["future_clicks", "recs"]).apply(calc_hitrate).alias("hitrate"),
    )
    #.filter(pl.col("hitrate").arr.get(2) == 1)
    .with_columns(pl.col("future_clicks").apply(len).alias("future_size"))
    #.filter(pl.col("future_size") > 10)
    .select(
        pl.col("recall").arr.get(0).mean().alias("recall@10"),
        pl.col("recall").arr.get(1).mean().alias("recall@100"),
        pl.col("recall").arr.get(2).mean().alias("recall@1000"),
        pl.col("precision").arr.get(0).mean().alias("precision@10"),
        pl.col("precision").arr.get(1).mean().alias("precision@100"),
        pl.col("precision").arr.get(2).mean().alias("precision@1000"),
        pl.col("hitrate").arr.get(0).mean().alias("hitrate@10"),
        pl.col("hitrate").arr.get(1).mean().alias("hitrate@100"),
        pl.col("hitrate").arr.get(2).mean().alias("hitrate@1000"),
        pl.col("hitrate").arr.get(0).sum().alias("hitrate_sum@10"), # количество рекомендаций, попавших в отложенную выборку
        pl.col("hitrate").arr.get(1).sum().alias("hitrate_sum@100"), # количество рекомендаций, попавших в отложенную выборку
        pl.col("hitrate").arr.get(2).sum().alias("hitrate_sum@1000") # количество рекомендаций, попавших в отложенную выборку
    )
    .head(5)
)

In [12]:
metrics # все пользователи ials v2

shape: (1, 12)
┌─────────┬──────────┬───────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ recall@ ┆ recall@1 ┆ recall@10 ┆ precision@ ┆ … ┆ hitrate@10 ┆ hitrate_su ┆ hitrate_su ┆ hitrate_su │
│ 10      ┆ 00       ┆ 00        ┆ 10         ┆   ┆ 00         ┆ m@10       ┆ m@100      ┆ m@1000     │
│ ---     ┆ ---      ┆ ---       ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ f64     ┆ f64      ┆ f64       ┆ f64        ┆   ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞═════════╪══════════╪═══════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 0.00148 ┆ 0.014637 ┆ 0.20322   ┆ 0.002248   ┆ … ┆ 0.626554   ┆ 2481.0     ┆ 18063.0    ┆ 72090.0    │
│ 2       ┆          ┆           ┆            ┆   ┆            ┆            ┆            ┆            │
└─────────┴──────────┴───────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [14]:
metrics # пользователи с более 5 кликами ials v2

shape: (1, 12)
┌─────────┬──────────┬───────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ recall@ ┆ recall@1 ┆ recall@10 ┆ precision@ ┆ … ┆ hitrate@10 ┆ hitrate_su ┆ hitrate_su ┆ hitrate_su │
│ 10      ┆ 00       ┆ 00        ┆ 10         ┆   ┆ 00         ┆ m@10       ┆ m@100      ┆ m@1000     │
│ ---     ┆ ---      ┆ ---       ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ f64     ┆ f64      ┆ f64       ┆ f64        ┆   ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞═════════╪══════════╪═══════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 0.00135 ┆ 0.01256  ┆ 0.186147  ┆ 0.003403   ┆ … ┆ 0.789638   ┆ 2300.0     ┆ 16257.0    ┆ 55810.0    │
│ 9       ┆          ┆           ┆            ┆   ┆            ┆            ┆            ┆            │
└─────────┴──────────┴───────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [17]:
metrics # пользователи с более 10 кликами ials v2

shape: (1, 12)
┌─────────┬──────────┬───────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ recall@ ┆ recall@1 ┆ recall@10 ┆ precision@ ┆ … ┆ hitrate@10 ┆ hitrate_su ┆ hitrate_su ┆ hitrate_su │
│ 10      ┆ 00       ┆ 00        ┆ 10         ┆   ┆ 00         ┆ m@10       ┆ m@100      ┆ m@1000     │
│ ---     ┆ ---      ┆ ---       ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ f64     ┆ f64      ┆ f64       ┆ f64        ┆   ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞═════════╪══════════╪═══════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 0.00120 ┆ 0.011286 ┆ 0.174333  ┆ 0.004121   ┆ … ┆ 0.843748   ┆ 2075.0     ┆ 14332.0    ┆ 44598.0    │
│ 1       ┆          ┆           ┆            ┆   ┆            ┆            ┆            ┆            │
└─────────┴──────────┴───────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [13]:
metrics # все пользователи

shape: (1, 12)
┌─────────┬──────────┬───────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ recall@ ┆ recall@1 ┆ recall@10 ┆ precision@ ┆ … ┆ hitrate@10 ┆ hitrate_su ┆ hitrate_su ┆ hitrate_su │
│ 10      ┆ 00       ┆ 00        ┆ 10         ┆   ┆ 00         ┆ m@10       ┆ m@100      ┆ m@1000     │
│ ---     ┆ ---      ┆ ---       ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ f64     ┆ f64      ┆ f64       ┆ f64        ┆   ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞═════════╪══════════╪═══════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 0.00177 ┆ 0.017717 ┆ 0.192791  ┆ 0.002555   ┆ … ┆ 0.615298   ┆ 2808.0     ┆ 20094.0    ┆ 70795.0    │
│ 1       ┆          ┆           ┆            ┆   ┆            ┆            ┆            ┆            │
└─────────┴──────────┴───────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [15]:
metrics # пользователи с более 5 кликами в будущем

shape: (1, 12)
┌─────────┬──────────┬───────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ recall@ ┆ recall@1 ┆ recall@10 ┆ precision@ ┆ … ┆ hitrate@10 ┆ hitrate_su ┆ hitrate_su ┆ hitrate_su │
│ 10      ┆ 00       ┆ 00        ┆ 10         ┆   ┆ 00         ┆ m@10       ┆ m@100      ┆ m@1000     │
│ ---     ┆ ---      ┆ ---       ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ f64     ┆ f64      ┆ f64       ┆ f64        ┆   ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞═════════╪══════════╪═══════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 0.00159 ┆ 0.014702 ┆ 0.175538  ┆ 0.003843   ┆ … ┆ 0.779054   ┆ 2585.0     ┆ 17873.0    ┆ 55062.0    │
└─────────┴──────────┴───────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [17]:
metrics # пользователи с более 10 кликами в будущем

shape: (1, 12)
┌─────────┬──────────┬───────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ recall@ ┆ recall@1 ┆ recall@10 ┆ precision@ ┆ … ┆ hitrate@10 ┆ hitrate_su ┆ hitrate_su ┆ hitrate_su │
│ 10      ┆ 00       ┆ 00        ┆ 10         ┆   ┆ 00         ┆ m@10       ┆ m@100      ┆ m@1000     │
│ ---     ┆ ---      ┆ ---       ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ f64     ┆ f64      ┆ f64       ┆ f64        ┆   ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞═════════╪══════════╪═══════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 0.00137 ┆ 0.013099 ┆ 0.163925  ┆ 0.004616   ┆ … ┆ 0.834951   ┆ 2313.0     ┆ 15629.0    ┆ 44133.0    │
│ 7       ┆          ┆           ┆            ┆   ┆            ┆            ┆            ┆            │
└─────────┴──────────┴───────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [19]:
metrics # пользователи с более 15 кликами в будущем

shape: (1, 12)
┌─────────┬──────────┬───────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ recall@ ┆ recall@1 ┆ recall@10 ┆ precision@ ┆ … ┆ hitrate@10 ┆ hitrate_su ┆ hitrate_su ┆ hitrate_su │
│ 10      ┆ 00       ┆ 00        ┆ 10         ┆   ┆ 00         ┆ m@10       ┆ m@100      ┆ m@1000     │
│ ---     ┆ ---      ┆ ---       ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ f64     ┆ f64      ┆ f64       ┆ f64        ┆   ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞═════════╪══════════╪═══════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 0.00122 ┆ 0.012155 ┆ 0.155446  ┆ 0.005207   ┆ … ┆ 0.86678    ┆ 2076.0     ┆ 13823.0    ┆ 36553.0    │
│ 6       ┆          ┆           ┆            ┆   ┆            ┆            ┆            ┆            │
└─────────┴──────────┴───────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [21]:
metrics # пользователи у которых хотя бы одна релеватная рекомендация

shape: (1, 12)
┌─────────┬──────────┬───────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ recall@ ┆ recall@1 ┆ recall@10 ┆ precision@ ┆ … ┆ hitrate@10 ┆ hitrate_su ┆ hitrate_su ┆ hitrate_su │
│ 10      ┆ 00       ┆ 00        ┆ 10         ┆   ┆ 00         ┆ m@10       ┆ m@100      ┆ m@1000     │
│ ---     ┆ ---      ┆ ---       ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ f64     ┆ f64      ┆ f64       ┆ f64        ┆   ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞═════════╪══════════╪═══════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 0.00287 ┆ 0.028794 ┆ 0.313329  ┆ 0.004153   ┆ … ┆ 1.0        ┆ 2808.0     ┆ 20094.0    ┆ 70795.0    │
│ 8       ┆          ┆           ┆            ┆   ┆            ┆            ┆            ┆            │
└─────────┴──────────┴───────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [19]:
metrics # без neural item2item

shape: (1, 12)
┌─────────┬──────────┬───────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ recall@ ┆ recall@1 ┆ recall@10 ┆ precision@ ┆ … ┆ hitrate@10 ┆ hitrate_su ┆ hitrate_su ┆ hitrate_su │
│ 10      ┆ 00       ┆ 00        ┆ 10         ┆   ┆ 00         ┆ m@10       ┆ m@100      ┆ m@1000     │
│ ---     ┆ ---      ┆ ---       ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ f64     ┆ f64      ┆ f64       ┆ f64        ┆   ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞═════════╪══════════╪═══════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 0.00170 ┆ 0.017079 ┆ 0.12575   ┆ 0.00249    ┆ … ┆ 0.50259    ┆ 2709.0     ┆ 18762.0    ┆ 57827.0    │
│ 5       ┆          ┆           ┆            ┆   ┆            ┆            ┆            ┆            │
└─────────┴──────────┴───────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [14]:
metrics # добавили neural item2item

shape: (1, 12)
┌─────────┬──────────┬───────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ recall@ ┆ recall@1 ┆ recall@10 ┆ precision@ ┆ … ┆ hitrate@10 ┆ hitrate_su ┆ hitrate_su ┆ hitrate_su │
│ 10      ┆ 00       ┆ 00        ┆ 10         ┆   ┆ 00         ┆ m@10       ┆ m@100      ┆ m@1000     │
│ ---     ┆ ---      ┆ ---       ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ f64     ┆ f64      ┆ f64       ┆ f64        ┆   ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞═════════╪══════════╪═══════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 0.00153 ┆ 0.015848 ┆ 0.131056  ┆ 0.002248   ┆ … ┆ 0.512316   ┆ 2466.0     ┆ 17750.0    ┆ 58946.0    │
│ 2       ┆          ┆           ┆            ┆   ┆            ┆            ┆            ┆            │
└─────────┴──────────┴───────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘